// Auto-generated by scan_results.py — do not edit
// Generated: 2026-04-12T14:59:06.478259
const SCAN_HISTORY = [
  {
    "file": "modern_meta_matrix_full.html",
    "tag": "dashboard",
    "ts": "2026-04-12T12:16:08+00:00",
    "type": "dashboard",
    "path": "modern_meta_matrix_full.html",
    "size_kb": 159.7
  },
  {
    "file": "boros_vs_affinity_s55555.txt",
    "d1": "Boros",
    "d2": "Affinity",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-12T12:12:42+00:00",
    "type": "bo3-log",
    "path": "replays/boros_vs_affinity_s55555.txt",
    "size_kb": 24.5
  },
  {
    "file": "replay_boros_vs_zoo.html",
    "d1": "Boros",
    "d2": "Zoo",
    "tag": "replay",
    "ts": "2026-04-12T11:17:44+00:00",
    "type": "replay",
    "path": "replays/replay_boros_vs_zoo.html",
    "size_kb": 140.1
  },
  {
    "file": "affinity_vs_azorius_control_s60006.txt",
    "d1": "Affinity",
    "d2": "Azorius Control",
    "seed": "60006",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/affinity_vs_azorius_control_s60006.txt",
    "size_kb": 34.1
  },
  {
    "file": "izzet_prowess_vs_boros_energy_s60004.txt",
    "d1": "Izzet Prowess",
    "d2": "Boros Energy",
    "seed": "60004",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/izzet_prowess_vs_boros_energy_s60004.txt",
    "size_kb": 32.1
  },
  {
    "file": "affinity_vs_boros_energy_s60001.txt",
    "d1": "Affinity",
    "d2": "Boros Energy",
    "seed": "60001",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/affinity_vs_boros_energy_s60001.txt",
    "size_kb": 24.9
  },
  {
    "file": "dimir_midrange_vs_boros_energy_s60005.txt",
    "d1": "Dimir Midrange",
    "d2": "Boros Energy",
    "seed": "60005",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/dimir_midrange_vs_boros_energy_s60005.txt",
    "size_kb": 51.8
  },
  {
    "file": "boros_energy_vs_living_end_s60002.txt",
    "d1": "Boros Energy",
    "d2": "Living End",
    "seed": "60002",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/boros_energy_vs_living_end_s60002.txt",
    "size_kb": 32.9
  },
  {
    "file": "eldrazi_tron_vs_boros_energy_s60003.txt",
    "d1": "Eldrazi Tron",
    "d2": "Boros Energy",
    "seed": "60003",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/eldrazi_tron_vs_boros_energy_s60003.txt",
    "size_kb": 53.8
  },
  {
    "file": "azorius_wst_vs_boros_s55555.txt",
    "d1": "Azorius Wst",
    "d2": "Boros",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-12T05:54:43+00:00",
    "type": "bo3-log",
    "path": "replays/azorius_wst_vs_boros_s55555.txt",
    "size_kb": 37.4
  },
  {
    "file": "metagame_results.json",
    "decks": 0,
    "n": 0,
    "tag": "matrix",
    "ts": "2026-04-11T20:15:38.108228",
    "type": "matrix",
    "path": "metagame_results.json",
    "size_kb": 3.0
  },
  {
    "file": "boros_energy_vs_domain_zoo_s55555.txt",
    "d1": "Boros Energy",
    "d2": "Domain Zoo",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/boros_energy_vs_domain_zoo_s55555.txt",
    "size_kb": 61.7
  },
  {
    "file": "affinity_vs_domain_zoo_s55555.txt",
    "d1": "Affinity",
    "d2": "Domain Zoo",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/affinity_vs_domain_zoo_s55555.txt",
    "size_kb": 37.0
  },
  {
    "file": "jeskai_blink_vs_affinity_s55555.txt",
    "d1": "Jeskai Blink",
    "d2": "Affinity",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/jeskai_blink_vs_affinity_s55555.txt",
    "size_kb": 33.3
  },
  {
    "file": "affinity_vs_izzet_prowess_s55555.txt",
    "d1": "Affinity",
    "d2": "Izzet Prowess",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/affinity_vs_izzet_prowess_s55555.txt",
    "size_kb": 26.2
  },
  {
    "file": "eldrazi_tron_vs_izzet_prowess_s55555.txt",
    "d1": "Eldrazi Tron",
    "d2": "Izzet Prowess",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/eldrazi_tron_vs_izzet_prowess_s55555.txt",
    "size_kb": 60.4
  },
  {
    "file": "ruby_storm_vs_affinity_s55555.txt",
    "d1": "Ruby Storm",
    "d2": "Affinity",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/ruby_storm_vs_affinity_s55555.txt",
    "size_kb": 25.3
  }
];
