// Auto-generated by scan_results.py — do not edit
// Generated: 2026-04-12T15:52:57.754863
const SCAN_HISTORY = [
  {
    "file": "replay_ruby_storm_vs_dimir_midrange_s60105.html",
    "d1": "Ruby Storm",
    "d2": "Dimir Midrange",
    "tag": "replay",
    "ts": "2026-04-12T15:52:43.616137",
    "type": "replay",
    "path": "replays/replay_ruby_storm_vs_dimir_midrange_s60105.html",
    "size_kb": 105.9
  },
  {
    "file": "replay_domain_zoo_vs_affinity_s60104.html",
    "d1": "Domain Zoo",
    "d2": "Affinity",
    "tag": "replay",
    "ts": "2026-04-12T15:52:43.579973",
    "type": "replay",
    "path": "replays/replay_domain_zoo_vs_affinity_s60104.html",
    "size_kb": 118.2
  },
  {
    "file": "replay_dimir_midrange_vs_boros_energy_s60103.html",
    "d1": "Dimir Midrange",
    "d2": "Boros Energy",
    "tag": "replay",
    "ts": "2026-04-12T15:52:43.546096",
    "type": "replay",
    "path": "replays/replay_dimir_midrange_vs_boros_energy_s60103.html",
    "size_kb": 85.2
  },
  {
    "file": "replay_izzet_prowess_vs_eldrazi_tron_s60102.html",
    "d1": "Izzet Prowess",
    "d2": "Eldrazi Tron",
    "tag": "replay",
    "ts": "2026-04-12T15:52:43.519433",
    "type": "replay",
    "path": "replays/replay_izzet_prowess_vs_eldrazi_tron_s60102.html",
    "size_kb": 73.3
  },
  {
    "file": "replay_boros_energy_vs_domain_zoo_s60101.html",
    "d1": "Boros Energy",
    "d2": "Domain Zoo",
    "tag": "replay",
    "ts": "2026-04-12T15:52:43.491961",
    "type": "replay",
    "path": "replays/replay_boros_energy_vs_domain_zoo_s60101.html",
    "size_kb": 121.7
  },
  {
    "file": "replay_affinity_vs_boros_energy_s60100.html",
    "d1": "Affinity",
    "d2": "Boros Energy",
    "tag": "replay",
    "ts": "2026-04-12T15:52:43.454077",
    "type": "replay",
    "path": "replays/replay_affinity_vs_boros_energy_s60100.html",
    "size_kb": 119.1
  },
  {
    "file": "ruby_storm_vs_dimir_midrange_s60105.txt",
    "d1": "Ruby Storm",
    "d2": "Dimir Midrange",
    "seed": "60105",
    "tag": "bo3",
    "ts": "2026-04-12T15:52:37.528957",
    "type": "bo3-log",
    "path": "replays/ruby_storm_vs_dimir_midrange_s60105.txt",
    "size_kb": 42.2
  },
  {
    "file": "domain_zoo_vs_affinity_s60104.txt",
    "d1": "Domain Zoo",
    "d2": "Affinity",
    "seed": "60104",
    "tag": "bo3",
    "ts": "2026-04-12T15:52:31.595154",
    "type": "bo3-log",
    "path": "replays/domain_zoo_vs_affinity_s60104.txt",
    "size_kb": 51.9
  },
  {
    "file": "dimir_midrange_vs_boros_energy_s60103.txt",
    "d1": "Dimir Midrange",
    "d2": "Boros Energy",
    "seed": "60103",
    "tag": "bo3",
    "ts": "2026-04-12T15:52:28.092832",
    "type": "bo3-log",
    "path": "replays/dimir_midrange_vs_boros_energy_s60103.txt",
    "size_kb": 34.8
  },
  {
    "file": "izzet_prowess_vs_eldrazi_tron_s60102.txt",
    "d1": "Izzet Prowess",
    "d2": "Eldrazi Tron",
    "seed": "60102",
    "tag": "bo3",
    "ts": "2026-04-12T15:52:24.182958",
    "type": "bo3-log",
    "path": "replays/izzet_prowess_vs_eldrazi_tron_s60102.txt",
    "size_kb": 29.3
  },
  {
    "file": "boros_energy_vs_domain_zoo_s60101.txt",
    "d1": "Boros Energy",
    "d2": "Domain Zoo",
    "seed": "60101",
    "tag": "bo3",
    "ts": "2026-04-12T15:52:19.540518",
    "type": "bo3-log",
    "path": "replays/boros_energy_vs_domain_zoo_s60101.txt",
    "size_kb": 51.8
  },
  {
    "file": "affinity_vs_boros_energy_s60100.txt",
    "d1": "Affinity",
    "d2": "Boros Energy",
    "seed": "60100",
    "tag": "bo3",
    "ts": "2026-04-12T15:52:13.801667",
    "type": "bo3-log",
    "path": "replays/affinity_vs_boros_energy_s60100.txt",
    "size_kb": 47.5
  },
  {
    "file": "metagame_results.json",
    "decks": 0,
    "n": 50,
    "tag": "matrix",
    "ts": "2026-04-12T15:48:39.763599",
    "type": "matrix",
    "path": "metagame_results.json",
    "size_kb": 10.7
  },
  {
    "file": "modern_meta_matrix_full.html",
    "tag": "dashboard",
    "ts": "2026-04-12T13:19:48+00:00",
    "type": "dashboard",
    "path": "modern_meta_matrix_full.html",
    "size_kb": 159.7
  },
  {
    "file": "boros_vs_affinity_s55555.txt",
    "d1": "Boros",
    "d2": "Affinity",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-12T12:12:42+00:00",
    "type": "bo3-log",
    "path": "replays/boros_vs_affinity_s55555.txt",
    "size_kb": 24.5
  },
  {
    "file": "replay_boros_vs_zoo.html",
    "d1": "Boros",
    "d2": "Zoo",
    "tag": "replay",
    "ts": "2026-04-12T11:17:44+00:00",
    "type": "replay",
    "path": "replays/replay_boros_vs_zoo.html",
    "size_kb": 140.1
  },
  {
    "file": "affinity_vs_azorius_control_s60006.txt",
    "d1": "Affinity",
    "d2": "Azorius Control",
    "seed": "60006",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/affinity_vs_azorius_control_s60006.txt",
    "size_kb": 34.1
  },
  {
    "file": "izzet_prowess_vs_boros_energy_s60004.txt",
    "d1": "Izzet Prowess",
    "d2": "Boros Energy",
    "seed": "60004",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/izzet_prowess_vs_boros_energy_s60004.txt",
    "size_kb": 32.1
  },
  {
    "file": "affinity_vs_boros_energy_s60001.txt",
    "d1": "Affinity",
    "d2": "Boros Energy",
    "seed": "60001",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/affinity_vs_boros_energy_s60001.txt",
    "size_kb": 24.9
  },
  {
    "file": "dimir_midrange_vs_boros_energy_s60005.txt",
    "d1": "Dimir Midrange",
    "d2": "Boros Energy",
    "seed": "60005",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/dimir_midrange_vs_boros_energy_s60005.txt",
    "size_kb": 51.8
  },
  {
    "file": "boros_energy_vs_living_end_s60002.txt",
    "d1": "Boros Energy",
    "d2": "Living End",
    "seed": "60002",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/boros_energy_vs_living_end_s60002.txt",
    "size_kb": 32.9
  },
  {
    "file": "eldrazi_tron_vs_boros_energy_s60003.txt",
    "d1": "Eldrazi Tron",
    "d2": "Boros Energy",
    "seed": "60003",
    "tag": "bo3",
    "ts": "2026-04-12T09:59:25+00:00",
    "type": "bo3-log",
    "path": "replays/eldrazi_tron_vs_boros_energy_s60003.txt",
    "size_kb": 53.8
  },
  {
    "file": "azorius_wst_vs_boros_s55555.txt",
    "d1": "Azorius Wst",
    "d2": "Boros",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-12T05:54:43+00:00",
    "type": "bo3-log",
    "path": "replays/azorius_wst_vs_boros_s55555.txt",
    "size_kb": 37.4
  },
  {
    "file": "boros_energy_vs_domain_zoo_s55555.txt",
    "d1": "Boros Energy",
    "d2": "Domain Zoo",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/boros_energy_vs_domain_zoo_s55555.txt",
    "size_kb": 61.7
  },
  {
    "file": "affinity_vs_domain_zoo_s55555.txt",
    "d1": "Affinity",
    "d2": "Domain Zoo",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/affinity_vs_domain_zoo_s55555.txt",
    "size_kb": 37.0
  },
  {
    "file": "jeskai_blink_vs_affinity_s55555.txt",
    "d1": "Jeskai Blink",
    "d2": "Affinity",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/jeskai_blink_vs_affinity_s55555.txt",
    "size_kb": 33.3
  },
  {
    "file": "affinity_vs_izzet_prowess_s55555.txt",
    "d1": "Affinity",
    "d2": "Izzet Prowess",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/affinity_vs_izzet_prowess_s55555.txt",
    "size_kb": 26.2
  },
  {
    "file": "eldrazi_tron_vs_izzet_prowess_s55555.txt",
    "d1": "Eldrazi Tron",
    "d2": "Izzet Prowess",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/eldrazi_tron_vs_izzet_prowess_s55555.txt",
    "size_kb": 60.4
  },
  {
    "file": "ruby_storm_vs_affinity_s55555.txt",
    "d1": "Ruby Storm",
    "d2": "Affinity",
    "seed": "55555",
    "tag": "bo3",
    "ts": "2026-04-11T18:22:14+02:00",
    "type": "bo3-log",
    "path": "replays/ruby_storm_vs_affinity_s55555.txt",
    "size_kb": 25.3
  }
];
