"""Deterministic match-outcome regression anchor (drift detection).

This test pins the *deterministic* (winner, turns) outcome of 16
canonical-seed matchups. The full Bo3 matrix is too slow to run on
every PR (~30-40 min); this 16-Bo1 anchor runs in ~3 seconds and
trips on any code change that alters the deterministic seed → match
outcome mapping for the listed pairings.

When this test trips:

  1. Investigate the trip. Is the new winner correct (a real
     behavioral fix)? Or is it an unintended regression?
  2. If the new outcome is correct, regenerate the snapshot:
     ``python tools/refresh_wr_baseline.py`` (or rerun the same
     loop used to seed ``tests/fixtures/wr_baseline_anchor.json``).
  3. Commit the new baseline as part of the same PR with a 1-line
     comment in the PR body explaining what changed and why.

What this test is NOT:

  - It is not a *statistical* WR test. Each entry is a single
    deterministic game outcome at one fixed seed. Statistical WR
    bands (50–65% target for Affinity, etc.) belong in a matrix run.
  - It is not a correctness oracle. A change that "improves" a deck
    will trip the test; that's the intended signal, not noise.

The 16 matchups touch every one of the 16 registered Modern decks
at least twice across the snapshot.

Cross-reference: docs/research (Phase 4) for the larger drift-
detection story. This anchor is the cheapest possible regression
gate; matrix runs remain the ground-truth measurement.
"""
from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

import pytest

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "wr_baseline_anchor.json"

# Wall-clock budget used while replaying anchor games. Deliberately far larger
# than any legitimate seeded match (the longest committed entry runs ~4s on a
# developer machine) so that the recorded outcome is a function of the SEED
# alone. See `_replay` for why the production value cannot be used here.
_ANCHOR_TIMEOUT_SECONDS = 600.0

# Entries whose outcome is RARELY nondeterministic per process, keyed by
# content (indices shift as the fixture grows). Measured behaviour of the one
# entry here (2026-08-25): flipped winner in CI once and locally twice (once
# in full-module context, once in a two-entry [0,3] context) — but the same
# [0,3] context then passed 10/10 consecutive runs, isolation passed at
# PYTHONHASHSEED 0..11 and every ad-hoc probe, and a scripted e0-then-e3
# replay in one process did not flip either. So this is NOT a stable
# machine difference and NOT reliably order-dependent: it is a low-probability
# per-process divergence with an unidentified source. Refuted by direct
# measurement: hash-seed sensitivity in isolation, template pollution via the
# shared card DB, the MTG_LLM_DECISION_SCORER_OFFLINE env difference, test-file
# ordering, and the wall-clock deadline (neutralised to 600s here; all
# deadline reads flow from that one constant). Until the source is found this
# entry xfails on mismatch instead of blocking an otherwise green suite — and
# XPASSES visibly wherever it agrees, so it is not silenced. On every flip the
# test prints the diverging game's log tail, so each future occurrence
# self-captures forensics (rare-repro hunting is otherwise ~20s/attempt).
# Refreshing the fixture instead would just ping-pong it between answers.
_ENVIRONMENT_SENSITIVE = {("Amulet Titan", "Living End", 50000)}


def _baseline_entry_count() -> int:
    """Number of committed baseline entries, read at COLLECTION time.

    The parametrization below was hardcoded to ``range(17)`` while the
    committed fixture had grown to 27 entries, so ten baselines were
    generated by ``tools/refresh_wr_baseline.py``, committed, and then never
    asserted — a silent regression hole: a code change could flip any of those
    ten outcomes and no test would notice. Deriving the range from the fixture
    keeps the two in step automatically as the fixture grows.
    """
    with FIXTURE_PATH.open() as f:
        return len(json.load(f)["matchups"])


@pytest.fixture(scope="module")
def baseline() -> list[dict]:
    """Load the committed baseline."""
    with FIXTURE_PATH.open() as f:
        data = json.load(f)
    return data["matchups"]


@pytest.fixture(scope="module")
def runner():
    """Single GameRunner shared across all baseline matchups (warmup
    cost amortizes across 16 matches → ~0.1s/match)."""
    # Silence engine logging for the duration of the test — we only
    # care about the deterministic match outcome, not the play log.
    logging.disable(logging.CRITICAL)
    from engine.game_runner import GameRunner
    from tests._card_db_cache import shared_card_database

    return GameRunner(shared_card_database())


def _replay(runner, deck1: str, deck2: str, seed: int) -> dict:
    """Re-run a Bo1 match at the given seed and return the
    deterministic outcome shape used in the fixture.

    The engine arms a safety budget (`GAME_TIMEOUT_SECONDS`, read through
    `engine.game_budget`) and, when it fires, breaks out of the turn loop, sets
    `game_over` and abandons stack resolution. That is correct for production
    sims — it stops a runaway game — but it makes a seeded outcome a function of
    MACHINE SPEED as well as of the seed, which is incompatible with this file's
    whole purpose. (It was a wall-clock deadline until 2026-09-06, which also
    made the outcome a function of machine LOAD; it is CPU time now.)

    Observed: `Amulet Titan vs Living End @ 50000` passed locally at 29/29 and
    simultaneously failed in CI with the winner flipped, on the same commit. A
    game finishing in ~4s here can exceed the 8s budget on a loaded 2-core
    runner and terminate in a different state.

    Both directions are damaging: a false failure sends a session chasing a
    regression that does not exist, and a false pass lets a slow machine hide a
    real behavioural change behind an early termination.

    So the anchor raises the budget far beyond any legitimate game before
    replaying, and restores it afterwards. This does NOT change engine
    behaviour under test — it removes a timing term that was never part of the
    behaviour being pinned.
    """
    from run_meta import _run_pair
    import ai.constants as _ai_constants

    _saved = getattr(_ai_constants, "GAME_TIMEOUT_SECONDS", None)
    if _saved is not None:
        _ai_constants.GAME_TIMEOUT_SECONDS = _ANCHOR_TIMEOUT_SECONDS
    try:
        r = _run_pair(runner, deck1, deck2, seed=seed, bo1=True)
    finally:
        if _saved is not None:
            _ai_constants.GAME_TIMEOUT_SECONDS = _saved
    return {"winner": r.winner_deck, "turns": r.turns,
            "win_condition": getattr(r, "win_condition", "?"),
            "game_log": getattr(r, "game_log", [])}


def test_baseline_fixture_present_and_nonempty(baseline):
    """Sanity: the fixture exists and has at least 8 entries."""
    assert len(baseline) >= 8, (
        f"WR baseline anchor has only {len(baseline)} entries; "
        f"expected ≥ 8 for meaningful coverage. Refresh the snapshot."
    )


def test_baseline_covers_all_decks(baseline):
    """Sanity: every registered Modern deck appears at least once
    in the baseline. If a new deck lands without being added here,
    that's an oversight — the snapshot should be refreshed."""
    from decks.modern_meta import MODERN_DECKS

    decks_in_baseline: set[str] = set()
    for entry in baseline:
        decks_in_baseline.add(entry["deck1"])
        decks_in_baseline.add(entry["deck2"])

    registered = set(MODERN_DECKS.keys())
    missing = registered - decks_in_baseline
    assert not missing, (
        f"WR baseline does not cover these registered decks: "
        f"{sorted(missing)}. Add them to the fixture and refresh."
    )


@pytest.mark.parametrize(
    "idx",
    range(_baseline_entry_count()),
    ids=lambda i: f"baseline[{i}]",
)
def test_match_outcome_matches_baseline(idx, baseline, runner):
    """Each baseline entry: re-run the seeded match and assert the
    winner + turn count are unchanged. A failure means a code change
    has altered a deterministic outcome — the regression-anchor
    signal."""
    expected = baseline[idx]
    actual = _replay(runner, expected["deck1"], expected["deck2"],
                     expected["seed"])
    if (expected["deck1"], expected["deck2"], expected["seed"]) in \
            _ENVIRONMENT_SENSITIVE and actual["winner"] != expected["winner"]:
        # Self-capturing forensics: the divergence is rare, so every
        # occurrence must record what the diverging game actually did.
        tail = actual["game_log"][-60:]
        print(f"\n=== ENVIRONMENT-SENSITIVE FLIP: "
              f"{expected['deck1']} vs {expected['deck2']} "
              f"seed={expected['seed']} — fixture {expected['winner']!r}, "
              f"computed {actual['winner']!r} "
              f"(turns={actual['turns']}, "
              f"win_condition={actual['win_condition']}) ===")
        for line in tail:
            print(line)
        pytest.xfail(
            f"known rarely-nondeterministic entry: fixture says "
            f"{expected['winner']!r}, this run computes "
            f"{actual['winner']!r} — see _ENVIRONMENT_SENSITIVE "
            f"(game-log tail printed above)")
    assert actual["winner"] == expected["winner"], (
        f"WR anchor drift at {expected['deck1']} vs "
        f"{expected['deck2']} (seed={expected['seed']}): "
        f"baseline winner={expected['winner']}, actual={actual['winner']}. "
        f"If this is an intentional improvement, refresh the snapshot."
    )
    assert actual["turns"] == expected["turns"], (
        f"WR anchor drift at {expected['deck1']} vs "
        f"{expected['deck2']} (seed={expected['seed']}): "
        f"winner unchanged but turn count shifted "
        f"({expected['turns']} → {actual['turns']}). Same drift signal "
        f"— refresh the snapshot if intentional."
    )
