"""
Modern Metagame Deck Database
Contains current top-tier Modern decklists based on March 2026 metagame data.
Each deck is a dict with mainboard (60 cards) and sideboard (15 cards).

Card names use MTGJSON naming convention:
- Double-faced cards: "Front // Back"
- Split cards: "Left // Right"

Deck lists and metagame shares are also available as JSON files in
decks/lists/ and decks/metagame.json. The JSON files are the source
of truth; the Python dicts below serve as fallback.
"""
from typing import Dict, List, Tuple

# Metagame share data for weighting in simulations
METAGAME_SHARES = {
    "Boros Energy": 21.1,
    "Jeskai Blink": 9.2,
    "Eldrazi Tron": 7.1,
    "Ruby Storm": 6.2,
    "Affinity": 6.1,
    "Izzet Prowess": 4.9,
    "Amulet Titan": 4.1,
    "Goryo's Vengeance": 3.6,
    "Living End": 3.6,
    "Domain Zoo": 2.9,
    "Dimir Midrange": 2.8,
    "4c Omnath": 3.5,
    "4/5c Control": 3.5,
}

# Full decklists: mainboard + sideboard
MODERN_DECKS: Dict[str, Dict[str, Dict[str, int]]] = {
    "Boros Energy": {
        "mainboard": {
            "Guide of Souls": 4,
            "Ocelot Pride": 4,
            "Ragavan, Nimble Pilferer": 4,
            "Ajani, Nacatl Pariah // Ajani, Nacatl Avenger": 4,
            "Voice of Victory": 2,
            "Phlage, Titan of Fire's Fury": 4,
            "Seasoned Pyromancer": 3,
            "Ranger-Captain of Eos": 2,
            "Galvanic Discharge": 4,
            "Thraben Charm": 2,
            "Goblin Bombardment": 3,
            "Blood Moon": 1,
            "Arena of Glory": 3,
            "Arid Mesa": 4,
            "Elegant Parlor": 2,
            "Marsh Flats": 4,
            "Sacred Foundry": 3,
            "Plains": 2,
            "Mountain": 1,
            "Windswept Heath": 3,
            "Inspiring Vantage": 1,
        },
        "sideboard": {
            "Orim's Chant": 2,
            "Celestial Purge": 2,
            "Wrath of the Skies": 2,
            "Blood Moon": 1,
            "Wear // Tear": 2,
            "Obsidian Charmaw": 3,
            "Rest in Peace": 2,
            "Tormod's Crypt": 1,
        },
    },
    "Jeskai Blink": {
        "mainboard": {
            "Ragavan, Nimble Pilferer": 4,
            "Snapcaster Mage": 2,
            "Solitude": 4,
            "Subtlety": 2,
            "Quantum Riddler": 4,
            "Teferi, Time Raveler": 2,
            "Lightning Bolt": 4,
            "Counterspell": 2,
            "Spell Snare": 1,
            "Prismatic Ending": 2,
            "Ephemerate": 4,
            "Force of Negation": 2,
            "Flooded Strand": 4,
            "Scalding Tarn": 4,
            "Hallowed Fountain": 2,
            "Steam Vents": 2,
            "Sacred Foundry": 1,
            "Island": 2,
            "Plains": 1,
            "Mountain": 1,
            "Arid Mesa": 3,
            "Mystic Gate": 2,
            "Celestial Colonnade": 2,
            "Fiery Islet": 2,
            "Spell Queller": 1,
        },
        "sideboard": {
            "Flusterstorm": 2,
            "Wear // Tear": 2,
            "Celestial Purge": 2,
            "Supreme Verdict": 2,
            "Mystical Dispute": 2,
            "Engineered Explosives": 1,
            "Jace, the Mind Sculptor": 1,
            "Rest in Peace": 2,
            "Tormod's Crypt": 1,
        },
    },
    "Ruby Storm": {
        "mainboard": {
            # Creatures / Cost Reducers
            "Ral, Monsoon Mage // Ral, Leyline Prodigy": 4,
            "Ruby Medallion": 4,
            # Rituals (net +2R each with Medallion)
            "Pyretic Ritual": 4,
            "Desperate Ritual": 4,
            "Manamorphose": 4,
            # Draw-2 spells (R each with Medallion — the combo engine)
            "Reckless Impulse": 4,
            "Wrenn's Resolve": 4,
            "Glimpse the Impossible": 3,
            # Card selection
            "Valakut Awakening // Valakut Stoneforge": 2,
            # Rebuy + Finisher access
            "Past in Flames": 3,
            "Wish": 2,
            # Storm finisher (1 main, extras in sideboard for Wish)
            "Grapeshot": 1,
            # Lands (18)
            "Scalding Tarn": 3,
            "Arid Mesa": 3,
            "Bloodstained Mire": 2,
            "Wooded Foothills": 2,
            "Mountain": 4,
            "Thundering Falls": 1,
            "March of Reckless Joy": 1,
            "Sacred Foundry": 1,
            "Sunbaked Canyon": 1,
            "Elegant Parlor": 2,
            "Gemstone Caverns": 1,
        },
        "sideboard": {
            "Grapeshot": 1,
            "Empty the Warrens": 1,
            "Past in Flames": 1,
            "Blood Moon": 1,
            "Meltdown": 1,
            "Orim's Chant": 4,
            "Prismatic Ending": 3,
            "Wear // Tear": 2,
            "Brotherhood's End": 1,
        },
    },
    "Affinity": {
        "mainboard": {
            "Mox Opal": 4,
            "Ornithopter": 4,
            "Springleaf Drum": 4,
            "Signal Pest": 4,
            "Memnite": 4,
            "Thought Monitor": 4,
            "Cranial Plating": 4,
            "Sojourner's Companion": 4,
            "Nettlecyst": 2,
            "Engineered Explosives": 2,
            "Darksteel Citadel": 4,
            "Treasure Vault": 2,
            "Urza's Saga": 4,
            "Silverbluff Bridge": 2,
            "Razortide Bridge": 2,
            "Tanglepool Bridge": 2,
            "Mistvault Bridge": 2,
            "Island": 1,
            "Spire of Industry": 3,
            "Frogmite": 2,
        },
        "sideboard": {
            "Metallic Rebuke": 2,
            "Haywire Mite": 2,
            "Dispatch": 2,
            "Ethersworn Canonist": 2,
            "Relic of Progenitus": 2,
            "Hurkyl's Recall": 2,
            "Spell Pierce": 2,
            "Torpor Orb": 1,
        },
    },
    "Eldrazi Tron": {
        "mainboard": {
            "Thought-Knot Seer": 4,
            "Reality Smasher": 4,
            "Endbringer": 2,
            "Walking Ballista": 2,
            "Matter Reshaper": 4,
            "Eldrazi Mimic": 4,
            "Chalice of the Void": 4,
            "Expedition Map": 4,
            "All Is Dust": 2,
            "Warping Wail": 2,
            "Ugin, the Spirit Dragon": 2,
            "Kozilek's Command": 2,
            "Urza's Tower": 4,
            "Urza's Mine": 4,
            "Urza's Power Plant": 4,
            "Eldrazi Temple": 4,
            "Cavern of Souls": 2,
            "Blast Zone": 1,
            "Wastes": 3,
            "Ghost Quarter": 2,
        },
        "sideboard": {
            "Ratchet Bomb": 2,
            "Warping Wail": 2,
            "Spatial Contortion": 2,
            "Relic of Progenitus": 3,
            "Trinisphere": 2,
            "Wurmcoil Engine": 2,
            "Pithing Needle": 2,
        },
    },
    "Amulet Titan": {
        "mainboard": {
            "Primeval Titan": 4,
            "Amulet of Vigor": 4,
            "Dryad of the Ilysian Grove": 4,
            "Azusa, Lost but Seeking": 2,
            "Arboreal Grazer": 4,
            "Summoner's Pact": 4,
            "Cultivator Colossus": 1,
            "Green Sun's Zenith": 2,
            "Explore": 2,
            "Simic Growth Chamber": 4,
            "Gruul Turf": 2,
            "Selesnya Sanctuary": 1,
            "Boros Garrison": 1,
            "Tolaria West": 2,
            "Radiant Fountain": 1,
            "Vesuva": 1,
            "Valakut, the Molten Pinnacle": 1,
            "Cavern of Souls": 1,
            "Forest": 3,
            "Boseiju, Who Endures": 2,
            "Castle Garenbrig": 1,
            "Urza's Saga": 2,
            "The Mycosynth Gardens": 1,
            "Hanweir Battlements // Hanweir, the Writhing Township": 1,
            "Slayers' Stronghold": 1,
            "Sunhome, Fortress of the Legion": 1,
            "Shifting Woodland": 1,
            "Mosswort Bridge": 1,
            "Bojuka Bog": 1,
            "Crumbling Vestige": 1,
            "Khalni Garden": 1,
            "Gemstone Mine": 2,
        },
        "sideboard": {
            "Force of Vigor": 3,
            "Warping Wail": 1,
            "Engineered Explosives": 1,
            "Tireless Tracker": 2,
            "Obstinate Baloth": 2,
            "Reclamation Sage": 1,
            "Boseiju, Who Endures": 1,
            "Cavern of Souls": 1,
            "Endurance": 2,
            "Collector Ouphe": 1,
        },
    },
    "Goryo's Vengeance": {
        "mainboard": {
            "Goryo's Vengeance": 4,
            "Griselbrand": 4,
            "Archon of Cruelty": 2,
            "Solitude": 4,
            "Ephemerate": 4,
            "Faithful Mending": 4,
            "Thoughtseize": 4,
            "Persist": 3,
            "Unmarked Grave": 4,
            "Undying Evil": 2,
            "Marsh Flats": 4,
            "Godless Shrine": 2,
            "Watery Grave": 1,
            "Hallowed Fountain": 1,
            "Silent Clearing": 2,
            "Flooded Strand": 4,
            "Swamp": 2,
            "Plains": 1,
            "Island": 1,
            "Concealed Courtyard": 4,
            "Leyline of Sanctity": 2,
            "Unburial Rites": 1,
        },
        "sideboard": {
            "Leyline of the Void": 4,
            "Flusterstorm": 2,
            "Wear // Tear": 2,
            "Teferi, Time Raveler": 2,
            "Prismatic Ending": 2,
            "Force of Negation": 2,
            "Rest in Peace": 1,
        },
    },
    "Domain Zoo": {
        "mainboard": {
            "Ragavan, Nimble Pilferer": 4,
            "Territorial Kavu": 4,
            "Scion of Draco": 4,
            "Nishoba Brawler": 4,
            "Leyline Binding": 4,
            "Tribal Flames": 4,
            "Lightning Bolt": 2,
            "Stubborn Denial": 2,
            "Phlage, Titan of Fire's Fury": 4,
            "Orcish Bowmasters": 2,
            "Windswept Heath": 4,
            "Arid Mesa": 4,
            "Stomping Ground": 1,
            "Sacred Foundry": 1,
            "Steam Vents": 1,
            "Breeding Pool": 1,
            "Blood Crypt": 1,
            "Hallowed Fountain": 1,
            "Temple Garden": 1,
            "Zagoth Triome": 1,
            "Raugrin Triome": 1,
            "Jetmir's Garden": 1,
            "Ziatora's Proving Ground": 1,
            "Forest": 1,
            "Mountain": 1,
            "Plains": 1,
            "Scalding Tarn": 2,
            "Misty Rainforest": 2,
        },
        "sideboard": {
            "Flusterstorm": 2,
            "Wear // Tear": 2,
            "Endurance": 2,
            "Engineered Explosives": 1,
            "Force of Vigor": 2,
            "Celestial Purge": 2,
            "Boseiju, Who Endures": 2,
            "Tormod's Crypt": 2,
        },
    },
    "Living End": {
        "mainboard": {
            "Living End": 4,
            "Shardless Agent": 4,
            "Demonic Dread": 4,
            "Force of Negation": 4,
            "Subtlety": 4,
            "Street Wraith": 4,
            "Striped Riverwinder": 4,
            "Architects of Will": 4,
            "Curator of Mysteries": 2,
            "Waker of Waves": 2,
            "Misty Rainforest": 4,
            "Verdant Catacombs": 4,
            "Breeding Pool": 1,
            "Watery Grave": 1,
            "Overgrown Tomb": 1,
            "Blood Crypt": 1,
            "Forest": 2,
            "Island": 2,
            "Swamp": 1,
            "Zagoth Triome": 1,
            "Ketria Triome": 1,
            "Indatha Triome": 1,
            "Raugrin Triome": 1,
            "Blooming Marsh": 2,
            "Botanical Sanctum": 1,
        },
        "sideboard": {
            "Foundation Breaker": 3,
            "Endurance": 3,
            "Mystical Dispute": 2,
            "Force of Vigor": 2,
            "Leyline of the Void": 3,
            "Boseiju, Who Endures": 2,
        },
    },
    "Izzet Prowess": {
        "mainboard": {
            # Creatures (12)
            "Dragon's Rage Channeler": 4,
            "Monastery Swiftspear": 4,
            "Slickshot Show-Off": 4,
            # Spells (30)
            "Lightning Bolt": 4,
            "Lava Dart": 4,
            "Unholy Heat": 2,
            "Mutagenic Growth": 4,
            "Violent Urge": 2,
            "Mishra's Bauble": 4,
            "Expressive Iteration": 4,
            "Preordain": 4,
            "Cori-Steel Cutter": 2,
            # Lands (18)
            "Scalding Tarn": 3,
            "Wooded Foothills": 3,
            "Arid Mesa": 2,
            "Bloodstained Mire": 2,
            "Steam Vents": 2,
            "Stomping Ground": 1,
            "Fiery Islet": 1,
            "Thundering Falls": 2,
            "Mountain": 2,
        },
        "sideboard": {
            "Consign to Memory": 4,
            "Pick Your Poison": 3,
            "Murktide Regent": 2,
            "Spell Pierce": 2,
            "Surgical Extraction": 2,
            "Meltdown": 1,
            "Spell Snare": 1,
        },
    },
    "Dimir Midrange": {
        "mainboard": {
            "Orcish Bowmasters": 4,
            "Psychic Frog": 4,
            "Subtlety": 2,
            "Murktide Regent": 4,
            "Thoughtseize": 4,
            "Fatal Push": 4,
            "Counterspell": 4,
            "Drown in the Loch": 2,
            "Consider": 4,
            "Spell Pierce": 2,
            "Archmage's Charm": 2,
            "Polluted Delta": 4,
            "Scalding Tarn": 2,
            "Watery Grave": 2,
            "Darkslick Shores": 4,
            "Island": 3,
            "Swamp": 1,
            "Otawara, Soaring City": 1,
            "Takenuma, Abandoned Mire": 1,
            "Underground River": 2,
            "Shelldock Isle": 1,
            "Creeping Tar Pit": 2,
            "Dauthi Voidwalker": 1,
        },
        "sideboard": {
            "Flusterstorm": 2,
            "Engineered Explosives": 1,
            "Mystical Dispute": 2,
            "Dress Down": 2,
            "Cling to Dust": 1,
            "Sheoldred, the Apocalypse": 2,
            "Nihil Spellbomb": 2,
            "Damnation": 1,
            "Tormod's Crypt": 2,
        },
    },
    "4c Omnath": {
        "mainboard": {
            # Lands (23)
            "Arena of Glory": 1,
            "Breeding Pool": 1,
            "Elegant Parlor": 1,
            "Flooded Strand": 4,
            "Hallowed Fountain": 1,
            "Hedge Maze": 1,
            "Island": 1,
            "Lush Portico": 1,
            "Misty Rainforest": 3,
            "Plains": 1,
            "Sacred Foundry": 1,
            "Steam Vents": 1,
            "Stomping Ground": 1,
            "Temple Garden": 1,
            "Thundering Falls": 1,
            "Windswept Heath": 3,
            # Creatures (16) — hybrid: shadow438 creature suite, balanced interaction
            "Endurance": 1,
            "Eternal Witness": 2,
            "Omnath, Locus of Creation": 3,
            "Phlage, Titan of Fire's Fury": 2,
            "Quantum Riddler": 4,
            "Solitude": 4,
            # Spells (21)
            "Ephemerate": 4,
            "Galvanic Discharge": 3,
            "Orim's Chant": 1,
            "Prismatic Ending": 3,
            "Stock Up": 2,
            "Teferi, Time Raveler": 3,
            "Wrath of the Skies": 2,
            "Wrenn and Six": 3,
        },
        "sideboard": {
            "Boseiju, Who Endures": 1,
            "Celestial Purge": 2,
            "Consign to Memory": 3,
            "Mystical Dispute": 4,
            "Surgical Extraction": 2,
            "Wear // Tear": 3,
        },
    },
    "4/5c Control": {
        "mainboard": {
            # Lands (23) — shadow438 mtgtop8 list
            "Arena of Glory": 1,
            "Breeding Pool": 1,
            "Elegant Parlor": 1,
            "Flooded Strand": 4,
            "Hallowed Fountain": 1,
            "Hedge Maze": 1,
            "Island": 1,
            "Lush Portico": 1,
            "Misty Rainforest": 3,
            "Plains": 1,
            "Sacred Foundry": 1,
            "Steam Vents": 1,
            "Stomping Ground": 1,
            "Temple Garden": 1,
            "Thundering Falls": 1,
            "Windswept Heath": 3,
            # Creatures (16)
            "Eternal Witness": 2,
            "Omnath, Locus of Creation": 3,
            "Phlage, Titan of Fire's Fury": 2,
            "Quantum Riddler": 4,
            "Solitude": 4,
            # Spells (21)
            "Ephemerate": 3,
            "Galvanic Discharge": 3,
            "Orim's Chant": 4,
            "Prismatic Ending": 2,
            "Stock Up": 2,
            "Teferi, Time Raveler": 3,
            "Wrath of the Skies": 2,
            "Wrenn and Six": 3,
        },
        "sideboard": {
            "Boseiju, Who Endures": 1,
            "Celestial Purge": 2,
            "Consign to Memory": 3,
            "Mystical Dispute": 4,
            "Surgical Extraction": 2,
            "Wear // Tear": 3,
        },
    },
}


def get_deck_list(deck_name: str) -> dict:
    """Get a deck by name. Returns dict with 'mainboard' and 'sideboard'."""
    return MODERN_DECKS.get(deck_name, {})


def get_all_deck_names() -> list:
    """Get all available deck names."""
    return list(MODERN_DECKS.keys())


def get_metagame_weights() -> dict:
    """Get metagame share percentages for weighting simulations."""
    return METAGAME_SHARES.copy()


def validate_deck(deck: dict) -> Tuple[bool, str]:
    """Validate a deck has 60 mainboard and 15 sideboard cards."""
    mainboard_count = sum(deck.get("mainboard", {}).values())
    sideboard_count = sum(deck.get("sideboard", {}).values())

    if mainboard_count < 60:
        return False, f"Mainboard has {mainboard_count} cards (need 60)"
    if sideboard_count > 15:
        return False, f"Sideboard has {sideboard_count} cards (max 15)"
    return True, "OK"
