#!/usr/bin/env python3
"""Mechanic coverage census — which keyword abilities and ability words
the pool uses, how many registered-deck cards carry each, and what the
engine has for it. Generated from the code, never hand-typed:

- `engine/rules_audit_census.KEYWORD_WORDS` is the vocabulary;
- a word is "enum" when `engine.cards.Keyword` has a member of that name,
  "typed field" when the loader populates a `CardTemplate` field for it
  (`rules_audit_census._FIELD_FOR_WORD`) on at least one card carrying the
  word, "handler" when every registered-deck card carrying the word has a
  dedicated `EFFECT_REGISTRY` handler, else "none";
- registered-deck usage counts copies across the 25 lists' mainboards and
  sideboards.

    python tools/keyword_coverage.py                # writes docs/design/rules_coverage.md
    python tools/keyword_coverage.py --stdout

The "none" rows ranked by registered-deck usage are the backlog of
mechanics the rules auditor cannot see because they are absent.
"""
from __future__ import annotations

import argparse
import datetime
import os
import sys
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

DOC_PATH = os.path.join(ROOT, "docs", "design", "rules_coverage.md")


def build_rows(db, decks):
    from engine.rules_audit_census import (KEYWORD_WORDS, _FIELD_FOR_WORD,
                                           _ENUM_NAMES, keyword_words)
    from engine.card_effects import EFFECT_REGISTRY, EffectTiming

    pool = Counter()
    deck_copies = Counter()
    deck_cards = defaultdict(set)
    field_seen = defaultdict(bool)
    handler_missing = defaultdict(set)

    for name, t in db.cards.items():
        words = list(keyword_words(t.oracle_text or ""))
        for w in words:
            pool[w] += 1
            f = _FIELD_FOR_WORD.get(w)
            if f and getattr(t, f, None):
                field_seen[w] = True

    for deck, spec in decks.items():
        for zone in ("mainboard", "sideboard"):
            for card, n in (spec.get(zone) or {}).items():
                t = db.get_card(card)
                if t is None:
                    continue
                for w in keyword_words(t.oracle_text or ""):
                    deck_copies[w] += n
                    deck_cards[w].add(card)
                    has_handler = any(EFFECT_REGISTRY.has_handler(card, tm)
                                      for tm in EffectTiming)
                    if not has_handler:
                        handler_missing[w].add(card)

    rows = []
    for w in KEYWORD_WORDS:
        if pool[w] == 0:
            continue
        if w in _ENUM_NAMES:
            status = "enum"
        elif field_seen[w]:
            status = f"typed field ({_FIELD_FOR_WORD[w]})"
        elif deck_cards[w] and not handler_missing[w]:
            status = "handler (every registered card)"
        else:
            status = "none"
        rows.append({
            "word": w, "pool": pool[w], "deck_copies": deck_copies[w],
            "deck_cards": len(deck_cards[w]), "status": status,
            "examples": ", ".join(sorted(deck_cards[w])[:3]),
        })
    rows.sort(key=lambda r: (r["status"] != "none", -r["deck_copies"], -r["pool"]))
    return rows


def render(rows, deck_count):
    today = datetime.date.today().isoformat()
    out = [
        "---",
        "title: Mechanic coverage census — keyword words in the pool vs the engine's model",
        "status: active",
        "priority: secondary",
        f"session: {today}",
        "tags:",
        "  - rules-audit",
        "  - coverage",
        "summary: >",
        "  Generated by tools/keyword_coverage.py. For every keyword-ability word the",
        "  pool uses: pool count, registered-deck usage (copies across MB+SB), and the",
        "  engine's status derived from the code (Keyword enum / typed field /",
        "  handler / none). The 'none' rows ranked by registered-deck usage are the",
        "  backlog of mechanics the rules auditor cannot see because they are absent.",
        "---",
        "",
        "# Mechanic coverage census",
        "",
        f"Generated {today} by `python tools/keyword_coverage.py` over the card DB and",
        f"the {deck_count} registered lists (MB + SB). Regenerate after a DB refresh or a",
        "new mechanic lands; do not edit by hand.",
        "",
        "Status is derived from the code's declared vocabulary only: a `Keyword` enum",
        "member, a typed `CardTemplate` field the loader populates, or a dedicated",
        "effect handler on every registered card carrying the word. A mechanic handled",
        "by a runtime oracle predicate (the metalcraft mana shape, for one) shows as",
        "`none` here until it gets a typed field — which is the migration this table",
        "exists to drive.",
        "",
        "| word | status | registered-deck copies | registered cards | pool cards | examples |",
        "|---|---|---:|---:|---:|---|",
    ]
    for r in rows:
        out.append(f"| {r['word']} | {r['status']} | {r['deck_copies']} | {r['deck_cards']} | "
                   f"{r['pool']} | {r['examples']} |")
    none_rows = [r for r in rows if r["status"] == "none"]
    out += ["", f"**{len(none_rows)} words with no model**, ranked by registered-deck usage: "
            + ", ".join(f"{r['word']} ({r['deck_copies']})" for r in none_rows[:15]) + "."]
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args(argv)
    from tests._card_db_cache import shared_card_database
    from decks.modern_meta import MODERN_DECKS
    db = shared_card_database()
    rows = build_rows(db, MODERN_DECKS)
    text = render(rows, len(MODERN_DECKS))
    if args.stdout:
        print(text)
    else:
        with open(DOC_PATH, "w") as f:
            f.write(text)
        print(f"wrote {DOC_PATH} ({len(rows)} words, "
              f"{sum(1 for r in rows if r['status'] == 'none')} with no model)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
